const COMMENT_MARKER = '<!-- eds-block-quality-reviewer -->';

function countBy(findings, field) {
  return findings.reduce((counts, finding) => ({
    ...counts,
    [finding[field]]: (counts[finding[field]] ?? 0) + 1,
  }), {});
}

function location(finding) {
  return finding.line ? `${finding.file}:${finding.line}` : finding.file;
}

function escapePipes(value) {
  return String(value).replaceAll('|', '\\|').replaceAll('\n', ' ');
}

function severityLabel(severity) {
  if (severity === 'error') return 'Error';
  if (severity === 'notice') return 'Notice';
  return 'Warning';
}

function renderSummary(findings) {
  const bySeverity = countBy(findings, 'severity');
  const byCategory = countBy(findings, 'category');
  return [
    `Findings: ${findings.length}`,
    `Errors: ${bySeverity.error ?? 0}`,
    `Warnings: ${bySeverity.warning ?? 0}`,
    `Notices: ${bySeverity.notice ?? 0}`,
    `LCP: ${byCategory.LCP ?? 0}`,
    `INP: ${byCategory.INP ?? 0}`,
    `CLS: ${byCategory.CLS ?? 0}`,
    `EDS: ${byCategory.EDS ?? 0}`,
  ].join(' | ');
}

function renderFindingDetails(findings) {
  return findings.map((finding, index) => {
    let section = `### ${index + 1}. ${finding.title}\n\n`;
    section += `- Severity: ${severityLabel(finding.severity)}\n`;
    section += `- Category: ${finding.category}\n`;
    section += `- Rule: \`${finding.rule_id}\`\n`;
    section += `- Location: \`${location(finding)}\`\n`;
    section += `- Why it matters: ${finding.message}\n`;
    section += `- Suggested action: ${finding.recommendation}\n`;
    if (finding.evidence) section += `- Evidence: \`${finding.evidence.slice(0, 240)}\`\n`;
    return section;
  }).join('\n');
}

function renderReport(findings, context = {}) {
  let body = `${COMMENT_MARKER}\n`;
  body += '## EDS Block Quality Review\n\n';
  body += 'This is a static PR review for AEM Edge Delivery Services block quality and Core Web Vitals risk. It does not replace Lighthouse, RUM, or manual review.\n\n';

  if (findings.length === 0) {
    body += 'No new EDS block quality concerns found on changed lines.\n\n';
    body += 'The reviewer looked for LCP, INP, CLS, and EDS best-practice risk signals.\n';
    return body;
  }

  body += `${renderSummary(findings)}\n\n`;
  body += '| Severity | Category | Location | Rule | Finding |\n';
  body += '|---|---|---|---|---|\n';
  findings.forEach((finding) => {
    body += `| ${severityLabel(finding.severity)} | ${finding.category} | \`${escapePipes(location(finding))}\` | \`${finding.rule_id}\` | ${escapePipes(finding.title)} |\n`;
  });
  body += '\n';
  body += renderFindingDetails(findings);

  if (context.truncated) {
    body += '\n\nMore findings were detected than the configured limit. Increase `max_findings` if you want the full list.';
  }

  body += '\n\n---\nGenerated by `aem-eds-block-quality-reviewer`.';
  return body;
}

export {
  COMMENT_MARKER,
  renderReport,
  renderSummary,
};
